### ISSUE TITLE
android 10 失效

### ISSUE THREAD

**Issue by imtianx** [nining377/UnblockMusicPro_Xposed#26]
之前 android 9 完美运行，换到 android 10（huawei mate 30 pro ）后无法使用，又遇到的么

**Comment by nining377** [comment]
无安卓10设备，无法测试

**Comment by imtianx** [comment]
华为的几款手机上用不了，是这个错误导致的么
```
2019-11-26 17:48:29.110 8502-8502/? I/ExposedBridge: Loading modules from /data/app/com.raincat.unblockmusicpro-Y9AcPh-9vtjbHNauXpHJwQ==/base.apk for process: com.netease.cloudmusic:core
2019-11-26 17:48:29.113 8592-8592/? I/ExposedBridge:   Loading class com.specher.music163.Hook
2019-11-26 17:48:29.119 8592-8592/? I/Xposed: music163plus:Loaded music163.
2019-11-26 17:48:29.121 8592-8592/? I/HwApiCacheMangerEx: apicache pi PackageInfo{5484c24 com.netease.cloudmusic}
2019-11-26 17:48:29.123 8592-8592/? I/Xposed: music163plus:versioncode:155
2019-11-26 17:48:29.133 8592-8592/? I/Xposed: replace Application.attach with ContextWrapper.attachBaseContext for CHA
2019-11-26 17:48:29.137 1153-1181/? I/HwAmbientLuxFilterAlgo:  Reset mAmbientLuxNewMax:mAmbientLux13.0, ambientLuxNewMaxBrightenDelta=5.2345915, mAmbientLuxNewMax=2.0216198
2019-11-26 17:48:29.138 1153-1181/? I/HwAmbientLuxFilterAlgo:  Reset mAmbientLuxNewMin:mAmbientLux13.0, ambientLuxNewMinBrightenDelta=5.2345915, mAmbientLuxNewMin=2.0216198
2019-11-26 17:48:29.159 8502-8502/? I/ExposedBridge:   Loading class com.raincat.unblockmusicpro.HTTPHook
2019-11-26 17:48:29.257 1153-1181/? I/HwAmbientLuxFilterAlgo:  Reset mAmbientLuxNewMax:mAmbientLux13.0, ambientLuxNewMaxBrightenDelta=5.2345896, mAmbientLuxNewMax=2.0216184
2019-11-26 17:48:29.258 1153-1181/? I/HwAmbientLuxFilterAlgo:  Reset mAmbientLuxNewMin:mAmbientLux13.0, ambientLuxNewMinBrightenDelta=5.2345896, mAmbientLuxNewMin=2.0216184
2019-11-26 17:48:29.261 8528-8528/? I/ExposedBridge: Loading modules from /data/app/com.raincat.unblockmusicpro-Y9AcPh-9vtjbHNauXpHJwQ==/base.apk for process: com.netease.cloudmusic:videoplay
2019-11-26 17:48:29.310 8558-8558/? I/ExposedBridge: Loading modules from /data/app/com.raincat.unblockmusicpro-Y9AcPh-9vtjbHNauXpHJwQ==/base.apk for process: com.netease.cloudmusic:cmMP1
2019-11-26 17:48:29.311 8502-8502/? I/DexposedBridge: java.lang.NoSuchMethodError: com.netease.cloudmusic.theme.core.ThemeInfo#o()#exact
        at de.robv.android.xposed.XposedHelpers.findMethodExact(SourceFile:351)
        at de.robv.android.xposed.XposedHelpers.findAndHookMethod(SourceFile:186)
        at com.specher.music163.d.afterHookedMethod(Unknown Source:558)
        at de.robv.android.xposed.ExposedHelper.afterHookedMethod(SourceFile:50)
        at de.robv.android.xposed.ଲଶଦ$ହ.afterHookedMethod(SourceFile:61)
        at de.robv.android.xposed.DexposedBridge.handleHookedArtMethod(SourceFile:275)
        at de.robv.android.xposed.DexposedBridge.handleHookedArtMethod(SourceFile:205)
        at android.content.ContextWrapper_1892176308.attachBaseContext(Unknown Source:18)
        at com.netease.cloudmusic.NeteaseMusicApplication.attachBaseContext(ProGuard:508)
        at java.lang.reflect.Method.invoke(Native Method)
        at me.weishu.epic.art2.EpicNative.invoke(Native Method)
        at de.robv.android.xposed.ଡଜ.ହ(SourceFile:248)
        at de.robv.android.xposed.DexposedBridge.invokeOriginalMethod(SourceFile:538)
        at de.robv.android.xposed.DexposedBridge.handleHookedArtMethod(SourceFile:259)
        at de.robv.android.xposed.DexposedBridge.handleHookedArtMethod(SourceFile:205)
        at com.netease.cloudmusic.NeteaseMusicApplication_3959968740.attachBaseContext(Unknown Source:18)
        at android.app.Application.attach(Application.java:200)
        at android.app.Instrumentation.newApplication(Instrumentation.java:1105)
        at android.app.Instrumentation.newApplication(Instrumentation.java:1089)
        at android.app.LoadedApk.makeApplication(LoadedApk.java:1053)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6590)
        at android.app.ActivityThread.-wrap2(Unknown Source:0)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2066)
        at android.os.Handler.dispatchMessage(Handler.java:108)
        at android.os.Looper.loop(Looper.java:166)
        at android.app.ActivityThread.main(ActivityThread.java:7529)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:245)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:921)
2019-11-26 17:48:29.314 8541-8541/? I/ExposedBridge: Loading modules from /data/app/com.raincat.unblockmusicpro-Y9AcPh-9vtjbHNauXpHJwQ==/base.apk for process: com.netease.cloudmusic:browser
2019-11-26 17:48:29.317 8502-8502/? I/HwApiCacheMangerEx: apicache pi PackageInfo{5484c24 com.netease.cloudmusic}
2019-11-26 17:48:29.317 8528-8528/? I/ExposedBridge:   Loading class com.raincat.unblockmusicpro.HTTPHook
2019-11-26 17:48:29.330 8502-8502/? I/HwApiCacheMangerEx: apicache oUid 10176
2019-11-26 17:48:29.330 8502-8502/? I/HwApiCacheMangerEx: apicache volumes [Landroid.os.storage.StorageVolume;@303455a
2019-11-26 17:48:29.331 8502-8502/? I/HwApiCacheMangerEx: apicache oUid 10176
2019-11-26 17:48:29.331 8502-8502/? I/HwApiCacheMangerEx: apicache volumes [Landroid.os.storage.StorageVolume;@303455a
2019-11-26 17:48:29.362 8558-8558/? I/ExposedBridge:   Loading class com.raincat.unblockmusicpro.HTTPHook
```

**Comment by Jieoz** [comment]
确实，Android10有显示运行成功但歌曲依旧灰色

**Comment by HellAction** [comment]
+1,相同情况

**Comment by HellAction** [comment]
最近脚本更新到0.25.3后,安卓10也可以正常使用了
